# Generated by Django 3.0.3 on 2023-05-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='accommodation',
            new_name='deal',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='nights',
            new_name='shifts',
        ),
    ]
