# Generated by Django 3.0.3 on 2023-04-30 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shifts', models.PositiveIntegerField(default=0, verbose_name='кол-во смен')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='время')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Deal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
